version: '3.0'

services:
  iceman-proxy:
    container_name: iceman-proxy
    image: nginx
    ports:
      - ${PROXY_PUBLIC_PORT}:80
    volumes:
      - ./build/nginx/templates:/etc/nginx/templates
      - ${ICEMAN_PROJECT}:/var/www/html/iceman
    environment:
      - ICEMAN_API_HOST=${ICEMAN_API_HOST}
      - APP_PORT=${APP_PORT}
    depends_on:
      - iceman-web
    networks:
      iceman-development:
        aliases:
          - ${ICEMAN_API_HOST}

  iceman-web:
    container_name: iceman-web
    build:
      context: ./build/node/serve
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:3000
    volumes:
      - ${ICEMAN_PROJECT}:/var/www/html/iceman
    working_dir: /var/www/html/iceman
    depends_on:
      - iceman-watch
    networks:
      iceman-development:
      
  iceman-watch:
    container_name: iceman-watch
    build:
      context: ./build/node/watch
      dockerfile: Dockerfile
    volumes:
      - ${ICEMAN_PROJECT}:/var/www/html/iceman
    working_dir: /var/www/html/iceman

networks:
  iceman-development:
    name: iceman-development