version: '3'

services:
  # proxy:
  #   container_name: proxy
  #   image: nginx
  #   extra_hosts:
  #     - 'host.docker.internal:host-gateway'
  #   ports:
  #     - '${PROXY_PUBLIC_PORT}:80'
  #   volumes:
  #     - './build/docker/nginx/conf.d:/etc/nginx/conf.d'
  #     - '${PROJECT_PATH}:/var/www/html/${PROJECT_NAME}'
  #   environment:
  #     API_HOST: '${API_HOST}'
  #     APP_PORT: '${APP_PORT}'
  #   depends_on:
  #     - serve
  #   networks:
  #     development:
  #       aliases:
  #         - ${API_HOST}

  # serve:
  #   container_name: serve
  #   build:
  #     context: ./build/docker/node/serve
  #     dockerfile: Dockerfile
  #   extra_hosts:
  #     - 'host.docker.internal:host-gateway'
  #   ports:
  #     - '${APP_PORT}:3001'
  #   volumes:
  #     - '${PROJECT_PATH}:/var/www/html/${PROJECT_NAME}'
  #   working_dir: /var/www/html/${PROJECT_NAME}
  #   depends_on:
  #     - database
  #   networks:
  #     - development

  database:
    container_name: database
    image: 'mariadb:latest'
    ports:
        - '${SQL_PORT:-3306}:3306'
    environment:
        MYSQL_ROOT_PASSWORD: '${SQL_PASSWORD}'
        MYSQL_ROOT_HOST: '%'
        MYSQL_DATABASE: '${SQL_DATABASE}'
        MYSQL_USER: '${SQL_USERNAME}'
        MYSQL_PASSWORD: '${SQL_PASSWORD}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
        - '${SQL_EPHEMERAL_STORAGE}:/var/lib/mysql'
    networks:
        - development

networks:
  development:
    name: development